{
  lib,
  pkgs,
  ...
}: {
  # Reuse the NVIDIA driver projected into WSL by Windows. Do not install a
  # Linux kernel driver inside WSL.
  wsl.useWindowsDriver = true;

  # NVIDIA's WSL utilities and Python/CUDA wheels use the conventional ELF
  # interpreter and expect the WSL driver libraries on the loader path.
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      stdenv.cc.cc
      zlib
    ];
  };

  environment.sessionVariables.LD_LIBRARY_PATH = ["/usr/lib/wsl/lib"];

  virtualisation.docker = {
    enable = true;
    enableOnBoot = true;
    daemon.settings = {
      features.cdi = true;
      live-restore = true;
    };
    # Do not auto-prune: the pinned SGLang image is digest-only and about
    # 60 GB unpacked, so Docker otherwise treats it as dangling when stopped.
    autoPrune.enable = false;
  };

  # CDI is the reliable way to expose the WSL GPU to NixOS containers. The
  # resulting device is referenced as: --device=nvidia.com/gpu=all
  hardware.nvidia-container-toolkit = {
    enable = true;
    discovery-mode = "wsl";
    suppressNvidiaDriverAssertion = true;

    # These executables come from the Windows driver projection, not from the
    # NixOS NVIDIA kernel-driver package.
    mount-nvidia-executables = false;
    mount-nvidia-docker-1-directories = false;

    # WSL CDI needs the symlink and ld-cache hooks generated by nvidia-ctk.
    disable-hooks = [];
  };

  # Make the host-side nvidia-smi binary convenient to invoke after nix-ld has
  # supplied its generic Linux ELF interpreter.
  environment.systemPackages = [
    (pkgs.writeShellScriptBin "nvidia-smi-wsl" ''
      export LD_LIBRARY_PATH=/usr/lib/wsl/lib''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      exec /usr/lib/wsl/lib/nvidia-smi "$@"
    '')
  ];
}
