name: Check

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  linux:
    name: NixOS and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting
        run: nix fmt -- --ci
      - name: Evaluate flake
        run: nix flake check --no-build

  macos:
    name: nix-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Evaluate flake
        run: nix flake check --no-build
